CREATE TABLE master_tracker.food (
	ID                    smallint AUTO_INCREMENT,
	food                  varchar(100) NOT NULL,
	serving_size          decimal(5,2) NOT NULL,
	serving_uom           varchar(20) NOT NULL,
	carbs                 decimal(5,2) NOT NULL,
	protein               decimal(5,2) NOT NULL,
	fats                  decimal(5,2) NOT NULL,
	calories              decimal(7,2) NOT NULL,
	brand                 varchar(100),
	cooking_type          varchar(100) NOT NULL,
	category              varchar(100) NOT NULL,
	subcategory           varchar(100) NOT NULL,
	fiber                 decimal(5,2),
	sugar                 decimal(5,2),
	saturated_fats        decimal(5,2),
	monounsaturated_fats  decimal(5,2),
	polyunsaturated_fats  decimal(5,2),
	trans_fats            decimal(5,2),
	omega_3               decimal(5,2),
	omega_6               decimal(5,2),
	cholesterol           decimal(5,2),
	histidine             decimal(5,2),
	isoleucine            decimal(5,2),
	leucine               decimal(5,2),
	lysine                decimal(5,2),
	methionine            decimal(5,2),
	phenylalanine         decimal(5,2),
	threonine             decimal(5,2),
	tryptophan            decimal(5,2),
	valine                decimal(5,2),
	arginine              decimal(5,2),
	vitamin_a             decimal(6,2),
	vitamin_b1            decimal(6,2),
	vitamin_b2            decimal(6,2),
	vitamin_b3            decimal(6,2),
	vitamin_b5            decimal(6,2),
	vitamin_b6            decimal(6,2),
	vitamin_b7            decimal(6,2),
	vitamin_b9            decimal(6,2),
	vitamin_b12           decimal(6,2),
	vitamin_c             decimal(6,2),
	vitamin_d             decimal(6,2),
	vitamin_e             decimal(6,2),
	vitamin_k             decimal(6,2),
	calcium               decimal(5,2),
	iron                  decimal(5,2),
	potassium             decimal(5,2),
	selenium              decimal(5,2),
	sodium                decimal(5,2),
	zinc                  decimal(5,2),
	alcohol               decimal(5,2),
	caffeine              decimal(5,2),
	CONSTRAINT food_pkey PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX food_idx
ON master_tracker.food (food);